### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Littlekunlun** [En73r/DBDEazyQTE#1]
What should I pay attention to when using this script? Why does it have no effect when I use it. What should the shortcut keys in the game be set to?

**Comment by En73r** [comment]
Normally you only need to start the program and it will be running at repairing mode by default. When you are playing the game and the skill check appears, the program will press `space`  for you at the right time.  
ps, the program may be recognized as a virus by windows defender because of controlling the keyboard. If it happened, you need to add the program to the whitelist

**Comment by Littlekunlun** [comment]
Thank you for your answer. Thank you very much
