### ISSUE TITLE
some advise

### ISSUE THREAD

**Issue by xanxus135** [En73r/DBDEazyQTE#4]
i see the source code is support 2k resolution ratio
so it could be support to 4k resolution ratio ? or user could be set config about the variable to support it ?

just some advise,sometime switch computer resolution ratio have a bit troublesome.

thx your code help me, played gaming now

**Comment by En73r** [comment]
Indeed, 4k resolution is not supported by this program yet. But it's because of that I don't have a 4k monitor and I don't know the corresponding variable values. You see, the size of the QTE area doesn't change as the same ratio as the resolution do. So I have to manually set the variable values in different resolutions, instead of just multiplying them by the ratio.  

You are very welcome to upload your screenshot which contains a QTE circle so that I can know the variable values of 4k resolution or more unknown resolutions.

If you want to add the config yourself, you can check out the code here:
https://github.com/En73r/DBDEazyQTE/blob/cba61d95a7a39ed781aa03b31b89977a1f4fb0e2/DBDEazyQTE.py#L524-L527
This code actually set the size of the cropped square(QTE area) for 2560x1600 and 1920x1080 separately.
`crop_w` and `crop_h` stand for the width and the height of the cropped square.

**Comment by xanxus135** [comment]
thx you reply me.
I have already uploaded the three screenshot images in here ,  while at same time i will be try to add the config then go into game debug variable values.

look forward to your subsequent improvement. :-)

[sceenshot(4k-h2160-w3840).zip](https://github.com/En73r/DBDEazyQTE/files/9845887/sceenshot.4k-h2160-w3840.zip)
